Repository elastic/elastic-agent-libs, pull requests merged in 2022-06, with the labels that each got.

#57 [automation] Update go release version 1.17.11
  .go-version
  .golangci.yml
Labels: automation, dependency

#60 Synchronize lint rules across repositories
  .golangci.yml
  dev-tools/mage/linter.go
  dev-tools/templates/.golangci.yml
  file/helper_other.go
  file/helper_test.go
  kibana/client.go
  match/matcher_test.go
  service/service.go
  transport/client.go
  transport/httpcommon/httpcommon.go
Labels: Team:Elastic-Agent-Data-Plane

#59 Remove empty string as default value for VerificationMode
  .gitignore
  CHANGELOG.md
  transport/tlscommon/types.go
  transport/tlscommon/types_test.go
Labels: Team:Elastic-Agent-Control-Plane, v8.4.0

#63 update changelog to fix pr link
  CHANGELOG.md
Labels: Team:Elastic-Agent-Data-Plane

#65 Fix bug introduced by mapstr optimization.
  CHANGELOG.md
  mapstr/mapstr.go
  mapstr/mapstr_test.go
Labels: Team:Elastic-Agent-Data-Plane
