Repository elastic/elastic-agent-libs, pull requests merged in 2022-05, with the labels that each got.

#48 Add CODEOWNERS, marking data plane as owners.
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Data-Plane

#50 Fix keystore secrets parsing when values contain commas.
  .gitignore
  go.mod
  go.sum
  keystore/file_keystore_test.go
  keystore/keystore.go
  keystore/keystore_test.go
Labels: bug

#53 automation: bump golang version
  .ci/Jenkinsfile
  .ci/bump-go-release-version.sh
Labels: Team:Automation

#56 Upgrade gopkg.in/yaml.v3 to v3.0.1.
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane
