Repository elastic/elastic-agent-libs, pull requests merged in 2022-02, with the labels that each got.

#9 fix: Use the workspace as HOME
  .ci/Jenkinsfile
Labels: bug

#10 Create linter configuration and address found issues
  .ci/Jenkinsfile
  .golangci.yml
  config/config.go
  config/flags.go
  config/flags_test.go
  file/helper_other.go
  file/helper_test.go
  file/rotator.go
  file/rotator_test.go
  go.mod
  logp/config.go
  logp/core.go
  logp/core_test.go
  logp/environment.go
  logp/eventlog_unsupported.go
  logp/eventlog_windows.go
  logp/global_test.go
  logp/level.go
  logp/selective_test.go
  logp/syslog_unix.go
  logp/syslog_unsupported.go
  magefile.go
  paths/paths.go
  str/stringset.go
Labels: Team:Elastic-Agent-Data-Plane

#11 Reorganise the magefile
  .ci/Jenkinsfile
  .golangci.yml
  magefile.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane
