Repository elastic/elastic-agent-libs, pull requests merged in 2022-10, with the labels that each got.

#84 [automation] Update go release version 1.18.7
  .go-version
  .golangci.yml
Labels: automation, dependency

#83 Make the NewX() monitoring variables safe to re-register
  monitoring/metrics.go
  monitoring/metrics_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, v8.6.0

#87 Improve shutdown logs
  CHANGELOG.md
  service/service.go
  service/service_windows.go
Labels: enhancement, 8.6-candidate
