Repository elastic/elastic-agent-libs, pull requests merged in 2023-09, with the labels that each got.

#148 Add Elastic-Api-Version header to kibana client
  kibana/client_config.go
Labels: bug, enhancement, Team:Elastic-Agent

#150 Add checks for serverless support
  kibana/client.go
Labels: Team:Elastic-Agent

#151 add idle_connection_timeout to HTTPTransportSettings
  transport/httpcommon/httpcommon.go
  transport/httpcommon/httpcommon_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#152 Add `source_uri` and `force` to `UpgradeAgentRequest`
  kibana/fleet.go
Labels: Team:Elastic-Agent
