Repository elastic/elastic-agent-libs, pull requests merged in 2024-12, with the labels that each got.

#259 Initialize the interval trigger
  file/helper_other.go
  file/rotator_test.go
  file/trigger.go
  file/trigger_test.go
Labels: bug, v8.18.0

#260 Introduce tlscommon.SetInsecureDefaults
  transport/tlscommon/versions_default.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Team:Elastic-Agent-Control-Plane

#258 Add integration build tag
  .buildkite/scripts/test.ps1
  .buildkite/scripts/test.sh
  file/helper_test.go
  kibana/url_test.go
  logp/core_linux_test.go
  mapstr/mapstr_test.go
  monitoring/opts_test.go
  monitoring/registry_test.go
  monitoring/visitor_expvar_test.go
  transform/typeconv/datetime_test.go
  transport/tlscommon/tls_test.go
Labels: Team:Elastic-Agent-Data-Plane, cleanup
