Repository elastic/elastic-agent-libs, pull requests merged in 2024-11, with the labels that each got.

#247 Add `AlterPath` and `Traverse` functions to mapstr.M
  mapstr/mapstr.go
  mapstr/mapstr_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#246 kibana: add CreateFleetServerHosts and CreateFleetProxy
  kibana/fleet.go
  kibana/fleet_integration_test.go
  kibana/fleet_test.go
Labels: Team:Elastic-Agent-Data-Plane

#249 Do not throw error if `alterFunc` does not change the original key
  mapstr/mapstr.go
  mapstr/mapstr_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#241 [BUG] do not output error message for connections closed due to timeout
  transport/logging.go
  transport/logging_test.go
Labels: Team:Elastic-Agent-Data-Plane

#254 [windows] - Introduce PdhGetRawCounterArrayW
  helpers/windows/pdh/pdh_query_windows.go
  helpers/windows/pdh/pdh_query_windows_test.go
  helpers/windows/pdh/pdh_windows.go
  helpers/windows/pdh/zpdh_windows.go
Labels: Team:Elastic-Agent-Data-Plane
