Repository elastic/elastic-agent-libs, pull requests merged in 2024-04, with the labels that each got.

#192 Add NewWithConfig init function to api/server.go
  api/server.go
Labels: Team:Elastic-Agent

#193 Add Addr() method to server
  api/server.go
Labels: Team:Elastic-Agent

#191 logp: add an in-memory logger
  logp/logger.go
  logp/logger_test.go
Labels: enhancement, Team:Elastic-Agent

#196 Add support for repacking and merging tls.Config structs
  transport/tlscommon/types.go
  transport/tlscommon/types_test.go
  transport/tlscommon/versions.go
Labels: enhancement, Team:Elastic-Agent

#195 upgraded go-sysinfo
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent

#197 Add repack support for ServerConfig.ClientAuth
  transport/tlscommon/server_config_test.go
  transport/tlscommon/types.go
Labels: enhancement, Team:Elastic-Agent

#198 Add both uint64 and int64 to tlscommon types unpack methods
  transport/tlscommon/server_config_test.go
  transport/tlscommon/tls_test.go
  transport/tlscommon/types.go
  transport/tlscommon/types_test.go
  transport/tlscommon/versions.go
  transport/tlscommon/versions_test.go
Labels: bug, Team:Elastic-Agent

#199 Update zap version
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, dependency

#171 [logp] Add typed loggers allowing log entries to go to different outputs
  logp/config.go
  logp/configure/logging.go
  logp/core.go
  logp/core_mock_test.go
  logp/core_test.go
  logp/selective_test.go
  logp/typedloggercore.go
Labels: Team:Elastic-Agent
