Repository elastic/elastic-agent-libs, pull requests merged in 2024-10, with the labels that each got.

#231 testing/certutil: add support to RSA
  dev-tools/mage/gotool/noticer.go
  dev-tools/mage/install.go
  dev-tools/mage/notice.go
  testing/certutil/certutil.go
  testing/certutil/certutil_test.go
  testing/certutil/cmd/main.go
Labels: Team:Elastic-Agent-Data-Plane

#229 Add optimized ReadAll function
  api/npipe/listener_windows_test.go
  api/server_test.go
  api/server_windows_test.go
  file/fileinfo_test.go
  file/helper_test.go
  iobuf/iobuf.go
  iobuf/iobuf_test.go
  keystore/file_keystore.go
  keystore/file_keystore_test.go
  keystore/keystore_test.go
  loader/config.go
  loader/config_test.go
  loader/discover_test.go
  periodic/ratelimited_test.go
  processors/dissect/dissect_test.go
  transport/tlscommon/ca_pinning_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Team:Elastic-Agent

#233 fix(logp): TestConfigureWithCore fails with Go 1.24
  logp/core_test.go
Labels: Team:Elastic-Agent-Data-Plane, cleanup

#234 [chore] - update agent policy schema to include `overrides` functionality.
  kibana/fleet.go
Labels: Team:Elastic-Agent-Data-Plane

#235 [fix] Update fleet agent policy
  kibana/fleet.go
Labels: Team:Elastic-Agent-Data-Plane

#240 certutil: add functional options
  testing/certutil/certutil.go
  testing/certutil/cmd/main.go
Labels: Team:Elastic-Agent-Control-Plane

#243 certutil: certificates are valid for 30 days and cli improvements
  testing/certutil/certutil.go
  testing/certutil/cmd/main.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#244 Add a function to perform case-insensitive search in mapstr.M
  mapstr/mapstr.go
  mapstr/mapstr_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane
