Repository elastic/elastic-agent-libs, pull requests merged in 2025-02, with the labels that each got.

#270 chore: add linter that denies importing math/rand
  .golangci.yml
  transport/tlscommontest/test_helper.go
  transport/util.go
Labels: Team:Elastic-Agent-Data-Plane

#278 feat(fips): Disable encrypted private key support when in FIPS mode
  transport/tlscommon/decrypt_block_fips.go
  transport/tlscommon/decrypt_block_nofips.go
  transport/tlscommon/tls.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#281 Add FIPS TLS encrypted private key tests
  .buildkite/pipeline.yml
  .buildkite/scripts/test.sh
  transport/tlscommon/diag_test.go
  transport/tlscommon/server_config_test.go
  transport/tlscommon/tls.go
  transport/tlscommon/tls_config_test.go
  transport/tlscommon/tls_fips_test.go
  transport/tlscommon/tls_nofips_test.go
  transport/tlscommon/tls_test.go
  transport/tlscommon/tlscommon_test.go
  transport/tlscommon/types_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Team:Elastic-Agent-Control-Plane

#283 fix(mapstr): cast inner maps to M on Clone
  mapstr/mapstr.go
  mapstr/mapstr_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane
