Repository elastic/elastic-agent-libs, pull requests merged in 2025-03, with the labels that each got.

#293 Fixes #292
  transport/httpcommon/diag.go
Labels: Team:Elastic-Agent-Data-Plane

#296 config: protect global configOpts with a mutex
  config/config.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#297 [Chore] Add functions required for single logger instance
  logp/configure/logging.go
  logp/core.go
  logp/logger.go
Labels: Team:Elastic-Agent-Data-Plane

#303 Update go to 1.24
  .go-version
  go.mod
Labels: Team:Elastic-Agent-Control-Plane

#304 Update linter to v1.64.8
  .github/workflows/golangci-lint.yml
  .golangci.yml
  dev-tools/mage/linter.go
Labels: Team:Elastic-Agent-Control-Plane
